[gwrite.4xidraw]
unit = "mm"
document_start = "G21\nG90\nM3 S15\nG4 P{{pen_up_delay}}\n"
layer_start = ";(Start Layer {layer_id})\n"
line_start = ";(Start Block)\n"
segment_first = """G00 X{x:.10f} Y{y:.10f}
M3 S80
G4 P{{pen_down_delay}}
"""
segment = """G01 X{x:.10f} Y{y:.10f} F{{pen_speed}}\n"""
line_end = """M3 S15
G4 P{{pen_up_delay}}
"""
document_end = """M3 S15
G4 P{{pen_up_delay}}
G00 X0 Y0
"""
invert_y = false